name: test-action
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with: 
         node-version: '14'
         check-latest: true
    - run: npm -v
      shell: bash
      

