name: test-action
runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run: echo test actions start
    - run: ls -a
    - run: echo test actions end
      

