name: schedule test
on: 
  workflow_dispatch:
  schedule: 
    - cron: '58 08 * * *' # once a day at 08:58 UTC
    - cron: '00 17 * * *' # 每天下午五点执行
jobs:
  schedule_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo test the schedule action